fully functional MLOps training pipeline YOLOv8 + MLflow + MinIO + K8s

diff --git a/k8s/dataset-sync-job.yaml b/k8s/dataset-sync-job.yaml
--- a/k8s/dataset-sync-job.yaml
+++ b/k8s/dataset-sync-job.yaml
@@ -6,28 +6,70 @@ metadata:
     app: dataset-sync
 spec:
   backoffLimit: 3
-  activeDeadlineSeconds: 300
+  activeDeadlineSeconds: 900
   template:
     metadata:
       labels:
         app: dataset-sync
     spec:
       restartPolicy: OnFailure
+
+      initContainers:
+      - name: init-dataset-dir
+        image: romangoldur/a62-sync:v13
+        imagePullPolicy: IfNotPresent
+        command: ["sh", "-c"]
+        args:
+          - |
+            echo "[INIT] Initialisation et ouverture des droits du volume Linux..."
+            mkdir -p /app/data
+            chmod -R 777 /app/data
+            echo "[INIT] Volume prêt pour DVC."
+        volumeMounts:
+        - name: dataset-volume
+          mountPath: /app/data
+
       containers:
       - name: sync-worker
-        image: romangoldur/a62-sync:v12
+        image: romangoldur/a62-sync:v13
+        imagePullPolicy: IfNotPresent
+
         securityContext:
           runAsUser: 0
           runAsGroup: 0
-        imagePullPolicy: IfNotPresent
+
         env:
         - name: AWS_ACCESS_KEY_ID
           value: "minioadmin"
         - name: AWS_SECRET_ACCESS_KEY
           value: "minioadmin"
+        - name: DVC_NO_SCM
+          value: "1"
+
         volumeMounts:
         - name: dataset-volume
-          mountPath: /workspace
+          mountPath: /app/data
+
+        command: ["/bin/sh"]
+        args:
+          - "-c"
+          - |
+            echo "[SYNC] === Démarrage de la synchronisation ==="
+            cd /app || exit 1
+
+            echo "[SYNC] Structure interne de /app dans l'image :"
+            ls -la
+
+            echo "[SYNC] Lancement du dvc pull..."
+            dvc pull --verbose
+            if [ $? -ne 0 ]; then
+                echo "[SYNC][ERROR] Échec du dvc pull"
+                exit 1
+            fi
+
+            echo "[SYNC] === Succès ! Fichiers synchronisés ==="
+            ls -R /app/data
+
         resources:
           requests:
             cpu: "250m"
@@ -35,6 +77,7 @@ spec:
           limits:
             cpu: "500m"
             memory: "512Mi"
+
       volumes:
       - name: dataset-volume
         persistentVolumeClaim:
